import ffmpeg from "fluent-ffmpeg";
import { Readable } from "node:stream";
import { logger } from "../../logger";

export class FFMpeg {
  static async init(): Promise<FFMpeg> {
    return import("@ffmpeg-installer/ffmpeg").then((ffmpegInstaller) => {
      ffmpeg.setFfmpegPath(ffmpegInstaller.path);
      logger.info("FFmpeg path set to:", ffmpegInstaller.path);
      return new FFMpeg();
    });
  }

  async saveNormalizedAudio(
    audio: ArrayBuffer,
    outputPath: string,
  ): Promise<string> {
    logger.debug("Normalizing audio for Whisper");
    const inputStream = new Readable();
    inputStream.push(Buffer.from(audio));
    inputStream.push(null);

    return new Promise((resolve, reject) => {
      ffmpeg()
        .input(inputStream)
        .audioCodec("pcm_s16le")
        .audioChannels(1)
        .audioFrequency(16000)
        .toFormat("wav")
        .on("end", () => {
          logger.debug("Audio normalization complete");
          resolve(outputPath);
        })
        .on("error", (error: unknown) => {
          logger.error(error, "Error normalizing audio:");
          reject(error);
        })
        .save(outputPath);
    });
  }

  async createMp3DataUri(audio: ArrayBuffer): Promise<string> {
    const inputStream = new Readable();
    inputStream.push(Buffer.from(audio));
    inputStream.push(null);
    return new Promise((resolve, reject) => {
      const chunk: Buffer[] = [];

      ffmpeg()
        .input(inputStream)
        .audioCodec("libmp3lame")
        .audioBitrate(128)
        .audioChannels(2)
        .toFormat("mp3")
        .on("error", (err) => {
          reject(err);
        })
        .pipe()
        .on("data", (data: Buffer) => {
          chunk.push(data);
        })
        .on("end", () => {
          const buffer = Buffer.concat(chunk);
          resolve(`data:audio/mp3;base64,${buffer.toString("base64")}`);
        })
        .on("error", (err) => {
          reject(err);
        });
    });
  }

    async getVideoMetadata(filePath: string): Promise<{ duration: number; width: number; height: number }> {
    return new Promise((resolve, reject) => {
      ffmpeg.ffprobe(filePath, (err, metadata) => {
        if (err) {
          reject(err);
          return;
        }
        const { duration, width, height } = metadata.streams[0];
        if (duration === undefined || width === undefined || height === undefined) {
          reject(new Error("Could not get video metadata"));
          return;
        }
        resolve({ duration: parseFloat(duration), width, height });
      });
    });
  }

  async saveToMp3(audio: ArrayBuffer, filePath: string): Promise<string> {
    const inputStream = new Readable();
    inputStream.push(Buffer.from(audio));
    inputStream.push(null);
    return new Promise((resolve, reject) => {
      ffmpeg()
        .input(inputStream)
        .audioCodec("libmp3lame")
        .audioBitrate(128)
        .audioChannels(2)
        .toFormat("mp3")
        .save(filePath)
        .on("end", () => {
          logger.debug("Audio conversion complete");
          resolve(filePath);
        })
        .on("error", (err) => {
          reject(err);
        });
    });
  }

  async burnSubtitles(
    videoPath: string,
    audioPath: string,
    captions: { text: string; startMs: number; endMs: number }[],
    outputPath: string,
  ): Promise<string> {
    const subtitlesPath = `${outputPath}.ass`; // Change to .ass
    let assContent = `[Script Info]
; Script generated by the Gemini CLI
Title: Short Video Subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H00000000,&H00000000,&H000000FF,1,0,0,0,100,100,0,0,1,2,2,5,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

    captions.forEach((caption) => {
      const startH = Math.floor(caption.startMs / 3600000);
      const startM = Math.floor((caption.startMs % 3600000) / 60000);
      const startS = Math.floor((caption.startMs % 60000) / 1000);
      const startC = Math.floor((caption.startMs % 1000) / 10); // Centiseconds

      const endH = Math.floor(caption.endMs / 3600000);
      const endM = Math.floor((caption.endMs % 3600000) / 60000);
      const endS = Math.floor((caption.endMs % 60000) / 1000);
      const endC = Math.floor((caption.endMs % 1000) / 10); // Centiseconds

      const formatTime = (h: number, m: number, s: number, c: number) =>
        `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${c.toString().padStart(2, '0')}`;

      const startTime = formatTime(startH, startM, startS, startC);
      const endTime = formatTime(endH, endM, endS, endC);

      assContent += `Dialogue: 0,${startTime},${endTime},Default,,0,0,0,,${caption.text}
`;
    });
    require("fs").writeFileSync(subtitlesPath, assContent);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .input(audioPath)
        .videoCodec("libx264")
        .audioCodec("aac")
        .outputOptions(`-vf ass=${subtitlesPath}`)
        .on("end", () => {
          logger.debug("Subtitles burned successfully");
          resolve(outputPath);
        })
        .on("error", (err) => {
          logger.error("Error burning subtitles:", err);
          reject(err);
        })
        .save(outputPath);
    });
  }
}
